apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 # Exposes container port
          # TODO:
          # a. Add a config map reference to your secrets
          env:
            - name: "POSTGRES_DB"
              valueFrom:
                configMapKeyRef:
                  key: "POSTGRES_DB"
                  name: "postgres-config"
            - name: "POSTGRES_USER"
              valueFrom:
                configMapKeyRef:
                  key: "POSTGRES_USER"
                  name: "postgres-config"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: "POSTGRES_PASSWORD"
                  name: "postgres-secret"
          # b. Add the following volumeMounts:
          volumeMounts:
          #        mountPath: /var/lib/postgresql/data
          #        name to be postgredb
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      # c. Add the persistent volume claim from postgres-persistent.yml
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
          

