apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: scavenger
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: "supersecret"

---

apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_PASSWORD"
              name: postgres-config