apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: opaque
data:
# TODO: Challenge + Extension
# convert the configmap into secrets and
# update the deployment to consume those secrets
  POSTGRES_PASSWORD: cHNsdGVzdA==
